name: Build site

on:
  push:
    branches: [ build_to_ghpages_branch ]
  pull_request:
    branches: [ build_to_ghpages_branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '10.15.3'
    - name: pre build
      run: npm ci
    - name: get the current state of the site
      uses: actions/checkout@master
      with:
        repository: coopdigital/build-your-own-radar
        token: ${{ secrets.repo_access }}
    - name: build site
      run: npm run test && npm run build
    - name: deploy
      run: |
        git add -A && \
        git config --global user.name "Github Actions CI" && \
        git config --global user.email automagic@actions.com && \
        git commit -m "${GITHUB_RUN_NUMBER} auto-pushed to github" && \
        git push https://${{ secrets.repo_access }}@github.com/coopdigital/build-your-own-radar.git master:master

