name: Build site

on:
  push:
    branches: [ build_to_ghpages_branch ]
  pull_request:
    branches: [ build_to_ghpages_branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '10.15.3'
    # extract branch name
    - name: Extract branch name
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    # extract branch name on pull request
    - name: Print branch name
      if: github.event_name == 'pull_request'
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

    # print branch name
    - name: Get branch name
      run: echo 'The branch name is' $BRANCH_NAME

    - name: pre build
      run: npm ci
    - name: build site
      run: npm run test && npm run build
    - name: deploy
      run: |
        git add -A && \
        git config --global user.name "Github Actions CI" && \
        git config --global user.email automagic@actions.com && \
        git commit -m "${GITHUB_RUN_NUMBER} auto-pushed to github" && \
        git push https://${{ secrets.repo_access }}@github.com/coopdigital/build-your-own-radar.git master:master

